### ISSUE TITLE
How to setup development environment ? 

### ISSUE THREAD

**Issue by Rayanfer32** [Nexusoft/nexus-mobile#15]
**Getting this error when i try to run** `npm run android`

```sh
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'D:\ReactNativeDev\nexus-mobile\android\app\build.gradle' line: 135

* What went wrong:
A problem occurred evaluating project ':app'.
> D:\ReactNativeDev\nexus-mobile\android\local.properties (The system cannot find the file specified)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run
with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run
with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

npm ERR! code 1
npm ERR! path D:\ReactNativeDev\nexus-mobile
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npx react-native run-android

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rayanf\AppData\Local\npm-cache\_logs\2021-04-14T04_40_25_783Z-debug.log

D:\ReactNativeDev\nexus-mobile>
```

**Comment by KenCorma** [comment]
Try my fix I just posted on my branch. 

Local.properties is a file that is not suppose to be tracked with git. And is used to hold custom environment variables. Another fix would to be just create this file and leave it blank. But the right fix is to see if it exists before importing, which I did. 

number 2 might of happened because 1 failed but if not there should be a build.gradle under android/app that contains compiledSdkVersion. 

Give that fix a try for 1 and let me know.

**Comment by Rayanfer32** [comment]
Its 1 am in the morning here in India.... Ill try this the first thing
tomorrow.

**Comment by Rayanfer32** [comment]
How do i pull your changes onto my local 
I had cloned `master `

I tried this 
```sh
git switch Kendal
git pull --rebase
```
build.gradle is not changed

**Comment by Rayanfer32** [comment]
> How do i pull your changes onto my local
> I had cloned `master `
> 
> I tried this
> 
> ```shell
> git switch Kendal
> git pull --rebase
> ```
> 
> build.gradle is not changed

Sorry i was looking into the top level `build.gradle`

**Comment by KenCorma** [comment]
> > How do i pull your changes onto my local
> > I had cloned `master `
> > I tried this
> > ```shell
> > git switch Kendal
> > git pull --rebase
> > ```
> > 
> > 
> > build.gradle is not changed
> 
> Sorry i was looking into the top level `build.gradle`

Yeah there are 2 build.gradles a bit confusing but that's part of reactnative/android project

**Comment by Rayanfer32** [comment]
**Whats there to configure in  NDK**
```sh
D:\ReactNativeDev\nexus-mobile\master\nexus-mobile>npm run android

> nexus-mobile@0.8.2-1 android
> npx react-native run-android

warn Package react-native-app-intro-slider has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-native-app-intro-slider\package.json'
Require stack:
- D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\config\resolveNodeModuleDir.js
- D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\releaseChecker\index.js
- D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\start\runServer.js
- D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\start\start.js
- D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\index.js
- D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js
- D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\react-native\cli.js
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1509 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...

> Configure project :app

Installing unimodules:
 unimodules-core@6.0.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\@unimodules\core
 unimodules-react-native-adapter@5.7.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\@unimodules\react-native-adapter
 expo-application@2.4.1 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-application
 expo-background-fetch@8.6.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-background-fetch
 expo-barcode-scanner@9.1.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-barcode-scanner
 expo-constants@9.3.5 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-constants
 expo-error-recovery@1.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-error-recovery
 expo-file-system@9.3.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-file-system
 expo-font@8.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-font
 expo-image-loader@1.3.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-image-loader
 expo-keep-awake@8.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-keep-awake
 expo-linear-gradient@8.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-linear-gradient
 expo-location@10.0.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-location
 expo-notifications@0.8.2 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-notifications
 expo-permissions@10.0.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-permissions
 expo-secure-store@9.3.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-secure-store
 expo-splash-screen@0.8.1 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-splash-screen
 expo-sqlite@8.5.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-sqlite
 expo-task-manager@8.6.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-task-manager
 expo-updates@0.4.1 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-updates
 expo-web-browser@8.6.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\expo-web-browser
 unimodules-app-loader@1.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\unimodules-app-loader
 unimodules-barcode-scanner-interface@5.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\unimodules-barcode-scanner-interface
 unimodules-camera-interface@5.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\unimodules-camera-interface
 unimodules-constants-interface@5.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\unimodules-constants-interface
 unimodules-face-detector-interface@5.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\unimodules-face-detector-interface
 unimodules-file-system-interface@5.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\unimodules-file-system-interface
 unimodules-font-interface@5.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\unimodules-font-interface
 unimodules-image-loader-interface@5.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\unimodules-image-loader-interface
 unimodules-permissions-interface@5.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\unimodules-permissions-interface
 unimodules-sensors-interface@5.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\unimodules-sensors-interface
 unimodules-task-manager-interface@5.4.0 from D:\ReactNativeDev\nexus-mobile\master\nexus-mobile\node_modules\unimodules-task-manager-interface

Found some duplicated unimodule packages. Installed the ones with the highest version number.
Make sure following dependencies of your project are resolving to one specific version:
 expo-constants
Warning: Failed to download any source lists!

Warning: IO exception while downloading manifest:
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.Socket.connect(Socket.java:607)
        at java.net.Socket.connect(Socket.java:556)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient$1.run(HttpClient.java:515)
        at sun.net.www.http.HttpClient$1.run(HttpClient.java:513)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:512)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:553)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
        at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.openUrl(DownloadCache.java:247)
        at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.downloadAndCache(DownloadCache.java:624)
        at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.openCachedUrl(DownloadCache.java:455)
        at com.android.sdklib.repository.legacy.LegacyDownloader.downloadAndStream(LegacyDownloader.java:61)
        at com.android.repository.impl.downloader.LocalFileAwareDownloader.downloadAndStream(LocalFileAwareDownloader.java:51)
        at com.android.repository.impl.manager.RemoteRepoLoaderImpl.lambda$fetchPackages$0(RemoteRepoLoaderImpl.java:139)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

> Configure project :app
Warning: Still waiting for package manifests to be fetched remotely.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> NDK not configured. Download it with SDK manager. Preferred NDK version is '21.1.6352462'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run
with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

npm ERR! code 1
npm ERR! path D:\ReactNativeDev\nexus-mobile\master\nexus-mobile
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npx react-native run-android

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rayanf\AppData\Local\npm-cache\_logs\2021-04-15T06_08_14_041Z-debug.log

D:\ReactNativeDev\nexus-mobile\master\nexus-mobile>
```

**Comment by KenCorma** [comment]
you will need to follow the instructions with android studio or android sdk on installing the NDK. 
If you already have that then you might need to set the environment variables for NDK

**Comment by Rayanfer32** [comment]
> you will need to follow the instructions with android studio or android sdk on installing the NDK.
> If you already have that then you might need to set the environment variables for NDK

Ohh I see , Trying this fix [https://stackoverflow.com/questions/40943764/gradle-sync-failed-ndk-not-configured-download-it-with-sdk-manager](url)

**Comment by KenCorma** [comment]
> > you will need to follow the instructions with android studio or android sdk on installing the NDK.
> > If you already have that then you might need to set the environment variables for NDK
> 
> Ohh I see , Trying this fix [https://stackoverflow.com/questions/40943764/gradle-sync-failed-ndk-not-configured-download-it-with-sdk-manager](url)

I think its easier to just create an local.properties file and fill it 

`## This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
#Mon Sep 28 16:27:42 MST 2020
ndk.dir=/usr/local/Caskroom/android-sdk/4333796/ndk/21.3.6528147
sdk.dir=/usr/local/Caskroom/android-sdk/4333796
#openssl.dir=/foo/bar`

**Comment by KenCorma** [comment]
When you have it figured out please close this issue, :)
